/**This class is automatically generated by LayaAirIDE, please do not make any modifications. */
package src {
	import laya.utils.ClassUtils;
	/**
	 * 游戏初始化配置
	 */
	public class GameConfig {
		public static var onWeiXin:Boolean=true;
		public static var weixinURL:String="https://6361-catpirate-data-a98557-1258046007.tcb.qcloud.la/gameRes/";

		//?sign=5d70318a18398985f3d464deba208c17&t=1543903960
		//?sign=20afb5b679a086b5baeb027e19b50720&t=1543903915
		public static var width:int = 640;
		public static var height:int = 1136;
		public static var scaleNum:Number=0.56;//宽高比

		public static var scaleMode:String = "noscale";//"fixedwidth";
		public static var screenMode:String = "vertical";//"none";
		public static var alignV:String = "middle";//"middle";
		public static var alignH:String = "center";
		public static var startScene:* = "test/TestScene.scene";
		public static var sceneRoot:String = "";
		public static var debug:Boolean = false;
		public static var stat:Boolean = true;
		public static var physicsDebug:Boolean = false;
		public static var exportSceneToJson:Boolean = true;
		
		public static function init():void {
			//注册Script或者Runtime引用
			var reg:Function = ClassUtils.regClass;
		}
		GameConfig.init();
	}
}